== はじめに

=== 背景

わたしはWebプログラミングを中心にいろいろ学んで作って楽しんでいる。ある学術団体の事務職員をしていて、その団体のインターネットホームページの管理を任された。そのサイトは古き良きHTMLサイトで、数十のHTMLファイルとCSSファイルから構成されている。たくさんのHTMLの中に `<head>` と `<nav>` と `<footer>` があって、ほとんど同じコードが重複して存在している。数年前、外部のWebデザイナに発注して初期構築したらしい。受託したデザイナが何らかのオーサリングツールでソースを書き、ビルドした成果物がApacheサーバのhtdocsフォルダの下に配置されている。デザイナがどういうツールを使ったのかはわからない。デザイナから発注主へソースコードを納入するということはしなかったようだ。たぶん発注した人が「ソースって何？納品しなくていいよ。よくわからないから」といったんじゃないかと推測している。

わたしはこのサイトにWhat’s News的な記事を追加するためにエディタでHTMLを修正しているが、このやり方でメンテナンスを続けるのはキビしいなあと感じている。近い将来、誰かにサイトの管理役を引き継ぐことになるだろう。その時HTMLの山をホイと渡してあとは知らんぷりするのは気がとがめる。今どきのソフトウェア技術を導入してホームページのメンテナンス作業を楽にしたい、と思った。

サイトのページをJSXで作り直してみた。それはもちろんできる。JSXならコンポーネント化することができてコードの重複を排除できるのがうれしい。しかしこのサイトをReactによる Single Page Application に移行したいわけではない。そもそも閲覧オンリーなサイトだからReactの会話的ユーザーインタフェースは必要ない。レンタルサーバー上のApacheサーバに静的HTMLとCSSを配置しただけの現状の構成を捨ててNode.jsのサーバに移行すべき理由がない。SPAにしたら「ホームページの応答が遅くなった」といわれるかもしれないし。さてどうしようか...と迷っているうちに link:https://minista.qranoko.jp/[minista] を見つけた。

[quote]
____

minista（ミニスタ）は、ReactのJSXとViteで100%静的なサイトを作るスタティックサイトジェネレーターです。
____

これ、わたしのニーズにあっているかもしれないと思った。ministaのドキュメント link:https://minista.qranoko.jp/docs/setup[”Setup”] を手始めにいろいろ試した。途中行き詰まったこともあった。ministaのGitHubレポジトリにissueを投げた。

* link:https://github.com/qrac/minista/issues/146#event-30162718761[build したらエラ〜発生: ReferenceError: document is not defined
 #146]

このissueにキスパートが応えてくれた。おおいに学ぶところがあった。

ministaの公式ドキュメントに詳細情報が書かれている。しかし未経験者が迷わず読み通せる初歩的な手引きがないとわたしは思った。そこで自分の経験をネタに Getting Started with minista を書くことにした。

=== 対象読者

* TypeScriptでWebアプリを開発するスキルを持っている人
* React JSXでページを書きたい、しかし最終的には静的HTMLサイトを作りたいと望んでいる人
* ministaをまだ知らない人

=== 記事を読むメリット

ReactのJSXとViteで100%静的なサイトを作るスタティックサイトジェネレーター link:https://minista.qranoko.jp/[minista] に入門することができる。ある程度のボリュームのある実行可能なサンプルコードに触れることができる。

