== 背景

わたしはWeb技術を中心にいろいろ作って楽しんでいる。ある学術団体の事務職員をしていて、その団体のインターネットホームページの管理を任された。そのサイトはいわゆる古き良きHTMLサイトで、数十のHTMLファイルとCSSファイルから構成されている。たくさんのHTMLの中に `<head>` と `<nav>` と `<footer>` があって、ほとんど同じコードが重複して存在している。外部のWebデザイナに発注して納品されたものだ。受託したデザイナがツールでソースを書きツールでビルドした成果物がApacheサーバのhtdocsディレクトリの下に配置されている。デザイナがどういうツールで納品物を作ったかはわからない。デザイナから発注主へソースを納入するということはしなかったようだ。多分「ソースって何？要らないよ、手に余るから」と発注主が言ったんじゃないかな。

わたしはときどきこのサイトに *What’s News* 的な記事を追加するべくHTMLをエディタで編集する。その時このままではメンテナンスが厳しいなあと感じている。近い将来、誰かにサイトの管理役を引き継ぐことになるだろう。その時HTMLの山をホイと渡してあとは知らんぷりするのは気がとがめる。今どきのソフトウェア技術を導入してホームページのメンテナンス作業を楽にしたい、と思った。

いくつかのページをJSXで作り直してみた。それはもちろんできる。JSXを導入すればコードをコンポーネント化することができてうれしい。しかしこのサイトをReactによる *Single Page Application* に移行したいのか？そうではない。これは閲覧向けの素朴なサイトで、Reactの高度なユーザーインタフェースは要らない。Apacheサーバに静的HTMLとCSSを配置しただけのサイトの現状構成を変えるべき理由がない。Reactアプリにしたら団体の人に「ホームページの応答が遅くなった」といわれるだろうし。どうしようか...

最近 link:https://minista.qranoko.jp/[minista] というソフトウェアを見つけた。

[quote]
____

minista（ミニスタ）は、ReactのJSXとViteで100%静的なサイトを作るスタティックサイトジェネレーターです。
____

これ、わたしのニーズに適っているかもしれないと思った。ministaのドキュメントの linik:https://minista.qranoko.jp/docs/setup[Setup] を手始めに色々試した。途中、行き詰まってしまい ministaのGitHubレポジトリにissueを投げたこともあった。

* link:https://github.com/qrac/minista/issues/146#event-30162718761[build したらエラ〜発生: ReferenceError: document is not defined
 #146]

このissueにたいしエキスパートが応えてくれて、大いに学ぶところがあった。ministaの公式ドキュメントは製品に関する詳細情報が盛られているが、初学者が読むべき初歩的な手引きが見当たらなかった。そこでわたしの経験をネタに Getting Started with minista を書きます。
