== 背景

わたしはWebプログラミングを中心にいろいろ学んで作って楽しんでいる。ある学術団体の事務職員をしていて、その団体のインターネットホームページの管理を任された。そのサイトは古き良きHTMLサイトで、数十のHTMLファイルとCSSファイルから構成されている。たくさんのHTMLの中に `<head>` と `<nav>` と `<footer>` があって、ほとんど同じコードが重複して存在している。数年前、外部のWebデザイナに発注して初期構築したらしい。受託したデザイナが何らかのオーサリングツールでソースを書き、ビルドした成果物がApacheサーバのhtdocsディレクトリの下に配置されている。デザイナがどういうツールを使ったのかはわからない。デザイナから発注主へソースコードを納入するということはしなかったようだ。たぶん発注主が「ソースって何？要らないよ。よくわからないから」と言ったんじゃないかと推測している。

わたしは今でも必要に応じてこのサイトにWhat’s News的な記事を追加するべくエディタでHTMLを修正している。このやり方でメンテナンスを続けるのは厳しいなあと感じている。近い将来、誰かにサイトの管理役を引き継ぐことになるだろう。その時HTMLの山をホイと渡してあとは知らんぷりするのは気がとがめる。今どきのソフトウェア技術を導入してホームページのメンテナンス作業を楽にしたい、と思った。

いくつかのページをJSXで作り直してみた。それはもちろんできる。JSXを導入すればコードをコンポーネント化することができてコードの重複を排除できるのがうれしい。しかしこのサイトをReactによる Single Page Application に移行したいと望んではいない。閲覧オンリーなサイトだからReactの会話的ユーザーインタフェースは必要ない。レンタルサーバー上のApacheサーバに静的HTMLとCSSを配置しただけの現状の構成を変えてNode.jsの上でサーバに移行すべき理由がない。SPAにしたらきっと団体の人に「ホームページの応答が遅くなった」といわれるだろうし。さてどうしようか...と迷走しているうちに link:https://minista.qranoko.jp/[minista] を見つけた。

[quote]
____

minista（ミニスタ）は、ReactのJSXとViteで100%静的なサイトを作るスタティックサイトジェネレーターです。
____

これ、わたしのニーズにあっているかもしれないと思った。ministaのドキュメント link:https://minista.qranoko.jp/docs/setup[”Setup”] を手始めにいろいろ試した。途中行き詰まってしまい ministaのGitHubレポジトリにissueを投げた。

* link:https://github.com/qrac/minista/issues/146#event-30162718761[build したらエラ〜発生: ReferenceError: document is not defined
 #146]

このissueにキスパートが応えてくれて大いに学ぶところがあった。

ministaの公式ドキュメントには製品に関する詳細な情報が盛られている。しかし未経験者が読むべき初歩的な手引きが見当たらないと思った。そこでわたしの経験をネタに Getting Started with minista を書くことにした。
