== my-minista-project

ministaの書き方を習うために少し中身のあるプロジェクトを作ろう。次のような方針のもとに:

1. １つきりではなく複数のページから成るサイトのサンプルを作ろう
2. トップページのURLパスは `/` とする。このほかにサブディレクトリを持つURLを作る。たとえば `/about/` のように。
3. 共通のレイアウトを作り、すべてのページがそれに従うこととする
4. レイアウトを `<head>` と `<nav>` と `<footer>` で構成する
5. レイアウトを表現するコンポーネントを各々独立した `.jsx` ファイルにする。一つのページを複数のコンポーネントの組み合わせで実現する。
6. CSSでページのスタイルを定義する。`<head>` と `<nav>` と `<footer>` の背景色を塗り分けて見やすくしよう。
7. コンテンツの一部として写真も表示しよう

`$ROOT` の下に `my-minista-project` を作ろう。プロジェクトフォルダの名前はユニークにしなければならないが、その他の手順は `minimal-minista-project` と作るのと同じ。

[source,shell]
----
$ cd $ROOT
$ bun create minista@latest my-minista-project -- --template minista.ts
$ cd my-minista-project
$ bun install
----

=== 1. `src/index.jsx` を削除する

`bun create minista@latest` コマンドに `--template minista.ts` とテンプレートを指定したので `src/index.tsx` ファイルが生成された。このファイルを削除してください。`my-minista-project` のためにこのファイルは不要だから。

=== 2. `vite.config.js` を書き換える

次に `vite.config.js` を次のように書きかえる。

[source,javascript]
----
include::../my-minista-project/vite.config.js[]
----

３つのministaプラグインを使おうとしています。ドキュメントをそれぞれ一読してください。

* link:https://minista.qranoko.jp/docs/plugins/ssg[pluginSsgのドキュメント]
* link:https://minista.qranoko.jp/docs/plugins/bundle[pluginBundleのドキュメント]
* link:https://minista.qranoko.jp/docs/plugins/beautify[pluginBeautifyのドキュメント]

`pluginSsg` と `pluginBundle` はministaプロジェクトではおそらく必ず使うことになる重要プラグインです。

**`pluginSsg` プラグインのオプションの設定と `my-minista-project` プロジェクトの実際のフォルダ構成とが整合性が取れていること** が重要だ。もしも `pluginSsg` の設定と実際のフォルダ構成が食い違っていると `bun run build` コマンドを実行した時にstatic site generationの処理が空振りするので、`dist` ディレクトリの中に期待したような成果物が作られないだろう。 

`my-minista-project` プロジェクトにおいてわたしは `pluginSsg` プラグインの設定を下記のように書きました。

[source,javascript]
----
  plugins: [
    pluginSsg({
      layout: "/src/layouts/index.{tsx,jsx}",
      src: ["/src/pages/**/*.{tsx,jsx,mdx,md}"],
      srcBases: ["/src/pages"],
    }),
----

実はこの設定は link:https://minista.qranoko.jp/docs/plugins/ssg#options[plusginSsg - 公式ドキュメント] に示されたデフォルト値と同じです。だから

[source,javascript]
----
  plugins: [
    pluginSsg(),
----

と書いても同じことです。`my-minista-project` では設定を明示的に書いたのは、ドキュメントをいちいち参照するよりもコードを読み返す方が楽だからです。

さて、plusginSsgの設定を上記のように決定したので、それに呼応してフォルダ構成がどうあるべきかが決まり、JSXファイルとCSSファイルと画像ファイルをどこに配置するかが決まります。

`pluginSsg` のオプションのデフォルト値がminista開発者の意見を反映していることは当然でしょう。

わたしは `my-minista-project` のフォルダ構成を下記のようにしました。

[source,shell]
----
$ tree -I 'node_modules|dist' my-minista-project
my-minista-project
├── bun.lock
├── package.json
├── src
│   ├── assets
│   │   ├── css
│   │   │   └── index.css
│   │   └── images
│   │       ├── 20210515111349_p.jpg
│   │       ├── 4467417.jpeg
│   │       └── seagull.jpg
│   ├── layouts
│   │   ├── footer.tsx
│   │   ├── header.tsx
│   │   ├── index.tsx
│   │   └── nav.tsx
│   └── pages
│       ├── about
│       │   └── index.tsx
│       └── index.tsx
├── tsconfig.json
└── vite.config.js
----

なぜこのようなフォルダ構成にしたのか？理由を説明します。

==== `src` ディレクトリ

ソースとしてのJSXファイルとCSSファイル画像ファイルをすべて `my-minista-project/src` ディレクトリの下に格納することにします。あとで `bun run build` コマンドを実行した時に成果物が `my-minista-project/dist` ディレクトリに出力されるはず。入力元としての`src` と出力先 `dist` というふうに二つを対照的に配置するのが見やすくて良い。

==== `src/layouts`

サイトのすべてのページが共通のレイアウトに従うように作るという設計方針にしたがい、レイアウトを規定するJSXファイル `my-minista-project/src/layouts/index.tsx` を作りました`pluginSsg` プラグインの `layout ` オプションが `layout: "/src/layouts/index.{tsx,jsx}",` と設定されていることと整合が取れていなければなりません。

`my-minista-project/src/layouts/index.tsx` のコードを下記のように書きました。

[source,typescript]
----
include::../my-minista-project/src/layouts/index.tsx[]
----

HTML要素 `<head>` を実装するJSXファイルを下記のように書きました。

[source,typescript]
----
include::../my-minista-project/src/layouts/header.tsx[]
----

`header.jsx` ファイルを `/src/layouts/` ディレクトリの中に配置しました。その一方でレイアウトを実装するJSXが 

`import { MyHeader } from "./header"`

とやってインポートしています。`header.jsx` が `my-minista-project/src/layouts/` ではない別の場所にあっても本来は構わない。`import` 文の `from "fffff"` を適切に書けば解決できる。しかしレイアウトを構成する複数のJSXを１箇所に集めた方が見通しが良い。そこで `header.jsx` を `src/layouts/` ディレクトリに配置した 。`nav` や `footer` についても同じ考えを適用した。

==== `src/pages/`

ページを実装するJSXファイルを `my-minista-project/src/pages/` ディレクトリの中に格納しました。Webサイトが起動した時に `my-minista-project/src/pages/index.tsx` ファイルがURL `http://localhost:xxxx/` に対応します。

`my-minista-project/src/pages/about/index.tsx` ファイルがURL `http://localhost:xxxx/about/` に対応します。このように `pages` ディレクトリの下のファイルの相対パスがURLのサブパスと一対一に対応します。

==== `srcBases`

`pluginSsg` プラグインの設定をこう書いた。

[source,typescript]
----
srcBases: ["/src/pages"],
----

ドキュメントの link:https://minista.qranoko.jp/docs/plugins/ssg#srcbases[srcBases] にこう書いてある。

[quote,text]
____
ページテンプレートをURLに変換する際に省くパス。前方一致で削除されます。
____

この設定があるので、ファイルパス `my-minista-project/src/pages/about/index.tsx` の中の `/src/pages` が省かれて `locahost:pppp/about/` というURLに対応づけられる、というルールが適用されます。

==== `src/assets/`

CSSファイルと画像ファイルを `my-minista-project/src/assets/` の中に格納しました。

